---
version: '3.8'
services:
  gateway:
    image: ${IMAGE_NAME:-apicast-test}
    depends_on:
    - one.upstream
    - two.upstream
    environment:
      APICAST_HTTPS_PORT: 8443
      APICAST_HTTPS_CERTIFICATE: /var/run/secrets/apicast/gateway.example.com.crt
      APICAST_HTTPS_CERTIFICATE_KEY: /var/run/secrets/apicast/gateway.example.com.key
      THREESCALE_CONFIG_FILE: /tmp/config.json
      THREESCALE_DEPLOYMENT_ENV: staging
      APICAST_CONFIGURATION_LOADER: lazy
      APICAST_WORKERS: 1
      APICAST_LOG_LEVEL: debug
      APICAST_CONFIGURATION_CACHE: "0"
    expose:
      - "8443"
      - "8090"
    ports:
      - "8443:8443"
      - "8090:8090"
    volumes:
      - ./apicast-config.json:/tmp/config.json
      - ./gateway-cert:/var/run/secrets/apicast
  one.upstream:
    image: alpine/socat:1.7.4.4
    container_name: one.upstream
    command: "-v openssl-listen:443,reuseaddr,fork,cert=/etc/pki/upstream.example.com.pem,verify=0,openssl-max-proto-version=TLS1.3 ssl:two.upstream:8005,verify=0"
    expose:
      - "443"
    restart: unless-stopped
    volumes:
      - ./upstream-cert/upstream.example.com.pem:/etc/pki/upstream.example.com.pem
  two.upstream:
    image: kalmhq/echoserver
    expose:
      - "8005"
